language: java

jdk:
  - openjdk8
  - openjdk11
  - openjdk12

cache:
  directories:
    - .autoconf
    - $HOME/.m2

script: "mvn verify"

jobs:
  include:
    - stage: "Tests and upload codecov, coveralls"     
      jdk: openjdk11
      script: "mvn test jacoco:report"
      after_script:
        - bash <(curl -s https://codecov.io/bash)
        - mvn coveralls:report
    - stage: "Build and push docker image"
      jdk: openjdk11
      services: docker
      script: mvn package docker:build -DskipTests
      after_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/samplespringbootapp:1.0-SNAPSHOT
        - docker push $DOCKER_USERNAME/samplespringbootapp:latest
        - echo "$DOCKER_BINTRAY_API" | docker login -u parj --password-stdin parj-docker-public-docker.bintray.io
        - docker tag $DOCKER_USERNAME/samplespringbootapp:1.0-SNAPSHOT parj-docker-public-docker.bintray.io/samplespringbootapp:1.0-SNAPSHOT
        - docker tag $DOCKER_USERNAME/samplespringbootapp:latest parj-docker-public-docker.bintray.io/samplespringbootapp:latest
        - docker push parj-docker-public-docker.bintray.io/samplespringbootapp:1.0-SNAPSHOT
        - docker push parj-docker-public-docker.bintray.io/samplespringbootapp:latest