language: java

jdk:
  - openjdk8
  - openjdk11
  - openjdk12

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.cache

script: "mvn verify"

jobs:
  include:
    - stage: "Tests and upload snapshot codecov, coveralls"     
      jdk: openjdk11
      script: "mvn test jacoco:report"
      after_script:
        - bash <(curl -s https://codecov.io/bash)
        - mvn coveralls:report

    - stage: "Deploy to ossrh"
      jdk: openjdk11
      script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -DskipTests"
        
    - stage: "Build and push docker image"
      jdk: openjdk11
      services: docker
      script: "mvn package docker:build -DskipTests"
      after_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/samplespringbootapp:1.0-SNAPSHOT
        - docker push $DOCKER_USERNAME/samplespringbootapp:latest