dist: bionic

language: java

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.cache
    - $TRAVIS_BUILD_DIR/target

env:
  - GPG_TTY=$(tty)

before_install:
- openssl aes-256-cbc -K $encrypted_a442ab25e147_key -iv $encrypted_a442ab25e147_iv
  -in .travis/gpg-private-key.asc.enc -out .travis/gpg-private-key.asc -d && gpg --batch --import .travis/gpg-private-key.asc
- sudo apt-get -y install gnupg-agent pinentry-gtk2 

script: "mvn install -DskipTests"
