language: java

jdk:
  - openjdk8
  - openjdk11
  - openjdk12

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.cache
    - $TRAVIS_BUILD_DIR/target

script: "mvn verify"

jobs:
  include:
    - stage: "Deploy to ossrh"
      jdk: openjdk11
      deploy:
        provider: script
        script: .travis/build.sh

    - stage: "Tests and upload snapshot codecov, coveralls"     
      jdk: openjdk11
      script: "mvn jacoco:report"
      after_script:
        - bash <(curl -s https://codecov.io/bash)
        - mvn coveralls:report

    - stage: "Build and push docker image"
      jdk: openjdk11
      services: docker
      script: "mvn docker:build"
      after_script:
        - echo "$DOCKER_BINTRAY_API" | docker login -u "$DOCKER_USERNAME" --password-stdin parj-docker-public-docker.bintray.io 
        - appVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        - echo "Version is ${appVersion}"
        - docker tag parjanya/samplespringbootapp:${appVersion} parj-docker-public-docker.bintray.io/samplespringbootapp:latest
        - docker push parj-docker-public-docker.bintray.io/samplespringbootapp:latest